### ISSUE TITLE
Schema Questions

### ISSUE THREAD

**Issue by Gytaco** [devonsparks/ifc-ld#2]
Hi Devon sorry a couple of other questions I thought might be best separated; happy to amalgamate if preferred.

Why use a Package vs a MVD label can those be consolidated as the same concept? Or are you considering these like a merge or save event?

Can slots have slots? I think if an Entity can have 1:N slots, then each slot can be 'tagged' then you don't need to manage a single version of ifc you can store all versions of slots by different parties and when you want to get the data out get the relevant slots by tags and or date. You might need to reconcile changes if there are duplicates, but it should be reasonably simple.

At the same 

Is a slot a single data point or can it be a group of attributes? Can it be both or is the idea you refer to IfcObjectDefinition for example as a slot or entity?

Slot naming for single attributes?
Rather then using ie "ifc4:person/4" a change to "ifc4:person/givenname" for a single attribute makes more sense.
This makes is more readable when looking at an individual item (don't need to look other references) and doesn't rely on ordered lists which is problematic.

Is the idea of Contents just to isolate the json relevant for ifc so it can be parsed back to STEP or others as required?

**Comment by devonsparks** [comment]
No worries @Gytaco. Appreciate the review.

A Package represents a set of changes. It's more than a label, because it has its own identity (a URI) and optionally a collection of metadata or other relationships. You could eschew Packages entirely and just tag Slots as belonging to the same set of changes, but it's useful (at least as a working hypothesis) that you may want to declare things about or relate to the change itself. That's what Packages permit.

re: can slots have slots? In principle, nothing would stop you from extending this, but I've intentionally left this out of the early drafts to see how far we can get without it. 

re: "I think if..." - Yes, this is how the spec works today. Slots can be tagged with a "group" field and capture basic provenance information (author, timestamp) in the (extensible) "meta" field. So it intends to work exactly as you describe.

Slots currently are meant to be atomic - just to test the limits of how simple the rules can be. A Slot might hold a literal value (like a string) or a relation (to another URI). Slot literals could be multi-valued (like an array of three floats representing an IfcColourRGB) but the value itself is atomic (an RGB color). Slot aggregation is currently handled through a separate tagging mechanism (see the "group" field in the spec), though this can be revisited. An individual IfcObjectDefinition would be an entity (because it has an ID derived from its IfcGUID) with a collection of Slots.

re: slot naming: the usage of offsets was to support graceful degradation for P21 translation. Otherwise, we can only translate versions of the schema we have on file, because the slot name is stored in the schema, not the P21 file. The consensus seems to be that this offset-based approach hurts more than it helps, so we're likely to remove that from the next draft and keep it in our back pocket if we need to use it later.

The usage of Contents is broader than just P21 conversion and serves two main purposes:

1. Contents separates what-a-Slot-holds from the Slot itself. There's information about the Slot (like provenance data) that exists independently of the particular value of its Contents. Having Contents go inside the Slot (like the _contents_ of a box or cell) supports this paradigm.
2. JSON-LD's syntax distinguishes URI references from literal values. Having a separate Contents object allows the rest of the Slot structure to be uniform, and delegates to the Contents object to provide information about its type. 

The relationship between Slots and Contents are also going under more review now.

IFC-LD "Objects" and "Slots" are likely to be renamed in the spec to "Entities" and "Components" to better align with adjacent bSI/IFC5 discussions.

**Comment by Gytaco** [comment]
Thanks for the Feedback Devon!
